# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='', max_length=128)),
                ('content', models.TextField(default='{}')),
                ('adtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='cid',
            field=models.CharField(default='', max_length=128),
        ),
    ]
