# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemonitor', '0002_auto_20170523_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualfile',
            name='fid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='baselinefile',
            name='fid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='actualfile',
            unique_together=set([('cid', 'fid')]),
        ),
        migrations.AlterUniqueTogether(
            name='baselinefile',
            unique_together=set([('cid', 'fid')]),
        ),
    ]
