# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemonitor', '0003_auto_20170523_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='category',
            field=models.CharField(default='', max_length=256),
        ),
    ]
