# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemonitor', '0004_config_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baselinefile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
