# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemonitor', '0006_auto_20170523_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
